### ISSUE TITLE
P100 plug is not working KLAP AUTHENTICATION 

### ISSUE THREAD

**Issue by GadgetAdict** [apatsufas/homebridge-tapo-p100#62]
[16/12/2024, 20:01:131 [Tapo P100] Trying KLAP Auth
[16/12/2024, 20:01:131
[Tapo P100] KLAP Handshake failed

**Comment by philipbcook** [comment]
Same here ..

[24/12/2024, 10:06:23] [Tapo Smart Platform] Trying KLAP Auth
[24/12/2024, 10:06:24] [Tapo Smart Platform] KLAP Handshake failed

Any progress on a fix ?

**Comment by JackHammer29** [comment]
Stuck here too

**Comment by philipbcook** [comment]
A bit of further diagnosis ...
I have an existing set of 6 x P100s that are configured and have been working via another PlugIn ( home bridge-tp-link-tapo ) which has discontinued support in October.  They all still work.  I configured 2 new P100s 3 days ago and although they work via the TAPO app on my phone, they will not function with either plugin ( home bridge-tp-link-tapo or homebridge-tapo ) in each case some form of handshake fails.  I think my iPhone TAPO app updated recently and wonder if TAPO have changed they way they register new devices in a way that is incompatible with how the homebridge plug-ins try to authenticate.

Just my thoughts.

**Comment by JackHammer29** [comment]
Mine started working again today

I updated my homebridge docker container to node 22, rebuilt the image while keeping the drive mappings.

also took the port mappings out so it’s in host mode - all good again

**Comment by philipbcook** [comment]
I am already running node v22.12.0 on a Raspberry Pi 5.
Still failing authentication with both plugins.
Have you tried configuring a new P100, is that working ?

**Comment by JackHammer29** [comment]
Haven’t tried configuring a new one but worth noting mine are only 1-2 months old anyway.

Have you checked the bulb’s IPs haven’t changed and are still matching the plugin config?

**Comment by philipbcook** [comment]
I have full control of IP addressing in my local network (I run dnsmasq).  All my TAPO devices are assigned fixed IP addresses and are on the addresses I configured in the homebridge plugins.

**Comment by undeat** [comment]
Hi,

i have the problems with KLAP, too. First i tried to use the P100 and P110 with Iobroker Homebrigde Plugin as Wrapper. That is not working and give no failure log. So i tried homebridge in a docker. I made a fresh setup. Node.js 22.14.0 is installed. Tapo P100 Plugin is @ 1.5.2.  Homebridge is at 1.9.0. I get the same messages like philipbcook.

[Tapo Smart Platform] Trying KLAP Auth
[Tapo Smart Platform] KLAP Handshake failed

what image should be rebuilded and how do i do that?

**Comment by undeat** [comment]
Ok i got it. Username is the e-mail adress and it is case sensitive!

**Comment by christopher-francisco** [comment]
I solved this:

1. Remove this plugin from HomeKit (go to bridges, remove it)
2. Remove all your non-working P100s from Tapo app 
3. In order to re-add them, **DO NOT** connect your P100 to your phone using the automated "Deviced found" prompt. Instead, cancel it, and go to the "+" button > "Add device" > "Yep, lights are green & orange" > select wifi and add password > etc...
4. Go to Homebridge > Plugins > this plugin's "more" button (which is an icon with vertical dots ...) > "Reset Accessories".
5. Go to Homebrdige > Home. You should no longer see KLAP error
6. Now your P100s should be working from Homebridge > Accessories. **Confirm they are working before adding the bridge (this plugin) back to HomeKit** so you don't lose time if one of them doesn't work
7. If one of them doesn't work. you probably didn't follow this steps STEP BY STEP. Apply the _don't think, just follow orders_ principle.

I don't know why this happens but I have some theories:
* Using the automatic "device connected" may be adding them to Tapo through a different mechanism other than IP address... they respond almost instantly, so perhaps that's why they don't work on bluetooth.
* And perhaps this mechanism enables some sort of internal flag that causes the KLAP auth (whatever that is) to fail

**Comment by GadgetAdict** [comment]
Thanks Christopher! That worked from first time!

**Comment by flamingtoast123** [comment]
100% solved my 'KLAP auth' issues with P110M units as well, thanks!

**Comment by njmyers** [comment]
Just tested this with a P105 (using P110 option in the plugin config) and it solved the KLAP issue.

**Comment by Cr0wTom** [comment]
For those still having issues, Tapo introduced opensource project support. I had the same issue till now, wasn't fixed by re-registering my devices, but on the settings go to Services -> Thirt-Party Services and enable Third-Party Compatibility. Restart your Homebridge and you will be good to go.

**Comment by crackseller** [comment]
Thank you [Cr0wTom](https://github.com/Cr0wTom)! That actually solved the issue. For clarification: Go to the Tapo app > Tap on "Me" > Scroll down to "Services" > Tap on "Third-Party Services" > At the bottom tap on "Third-Party Compatibility" > Switch it "On". Restart Homebridge and KLAP auth works again.

**Comment by FickleLife** [comment]
I tried enabling 3rd party integrations, rebooting homebridge but am still getting KLAP auth failed... I'll try the longer process above and see if the combination of both works.

**Comment by mrkingdevil** [comment]
thanks @Cr0wTom that solved months of headaches
